# Generated by Django 2.2.2 on 2019-06-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_type', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=128)),
                ('desc', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=128)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
    ]
