# Generated by Django 2.2.2 on 2019-06-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicmaps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='address',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='map',
            name='category',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='map',
            name='desc',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='map',
            name='map_type',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='map',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
